export enum NotificationType {
  INFO = 'INFO',
  WARNING = 'WARNING',
  ALERT = 'ALERT',
  SUCCESS = 'SUCCESS',
}

export enum NotificationCategory {
  LOW_STOCK = 'LOW_STOCK',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
  NEW_SALE = 'NEW_SALE',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  PURCHASE_COMPLETED = 'PURCHASE_COMPLETED',
  STOCK_ADJUSTMENT = 'STOCK_ADJUSTMENT',
  SYSTEM = 'SYSTEM',
}
