export enum CentralTransactionType {
  SALE = 'SALE',
  PURCHASE = 'PURCHASE',
  SALE_RETURN = 'SALE_RETURN',
  PURCHASE_RETURN = 'PURCHASE_RETURN',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  PAYMENT_SENT = 'PAYMENT_SENT',
  EXPENSE = 'EXPENSE',
  STOCK_ADJUSTMENT = 'STOCK_ADJUSTMENT',
}
